/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: query_response.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "query_response.pb-c.h"
void   query_response__init
                     (QueryResponse         *message)
{
  static const QueryResponse init_value = QUERY_RESPONSE__INIT;
  *message = init_value;
}
size_t query_response__get_packed_size
                     (const QueryResponse *message)
{
  assert(message->base.descriptor == &query_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t query_response__pack
                     (const QueryResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &query_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t query_response__pack_to_buffer
                     (const QueryResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &query_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
QueryResponse *
       query_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (QueryResponse *)
     protobuf_c_message_unpack (&query_response__descriptor,
                                allocator, len, data);
}
void   query_response__free_unpacked
                     (QueryResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &query_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   value__init
                     (Value         *message)
{
  static const Value init_value = VALUE__INIT;
  *message = init_value;
}
size_t value__get_packed_size
                     (const Value *message)
{
  assert(message->base.descriptor == &value__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t value__pack
                     (const Value *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &value__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t value__pack_to_buffer
                     (const Value *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &value__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Value *
       value__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Value *)
     protobuf_c_message_unpack (&value__descriptor,
                                allocator, len, data);
}
void   value__free_unpacked
                     (Value *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &value__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   result__init
                     (Result         *message)
{
  static const Result init_value = RESULT__INIT;
  *message = init_value;
}
size_t result__get_packed_size
                     (const Result *message)
{
  assert(message->base.descriptor == &result__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t result__pack
                     (const Result *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &result__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t result__pack_to_buffer
                     (const Result *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &result__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Result *
       result__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Result *)
     protobuf_c_message_unpack (&result__descriptor,
                                allocator, len, data);
}
void   result__free_unpacked
                     (Result *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &result__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   counted_result__init
                     (CountedResult         *message)
{
  static const CountedResult init_value = COUNTED_RESULT__INIT;
  *message = init_value;
}
size_t counted_result__get_packed_size
                     (const CountedResult *message)
{
  assert(message->base.descriptor == &counted_result__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t counted_result__pack
                     (const CountedResult *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &counted_result__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t counted_result__pack_to_buffer
                     (const CountedResult *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &counted_result__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CountedResult *
       counted_result__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CountedResult *)
     protobuf_c_message_unpack (&counted_result__descriptor,
                                allocator, len, data);
}
void   counted_result__free_unpacked
                     (CountedResult *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &counted_result__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor query_response__field_descriptors[2] =
{
  {
    "values",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(QueryResponse, n_values),
    offsetof(QueryResponse, values),
    &value__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "operations",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(QueryResponse, n_operations),
    offsetof(QueryResponse, operations),
    &aggregate__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned query_response__field_indices_by_name[] = {
  1,   /* field[1] = operations */
  0,   /* field[0] = values */
};
static const ProtobufCIntRange query_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor query_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "QueryResponse",
  "QueryResponse",
  "QueryResponse",
  "",
  sizeof(QueryResponse),
  2,
  query_response__field_descriptors,
  query_response__field_indices_by_name,
  1,  query_response__number_ranges,
  (ProtobufCMessageInit) query_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor value__field_descriptors[2] =
{
  {
    "grouping_value",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Value, grouping_value),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "results",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Value, n_results),
    offsetof(Value, results),
    &result__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned value__field_indices_by_name[] = {
  0,   /* field[0] = grouping_value */
  1,   /* field[1] = results */
};
static const ProtobufCIntRange value__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor value__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Value",
  "Value",
  "Value",
  "",
  sizeof(Value),
  2,
  value__field_descriptors,
  value__field_indices_by_name,
  1,  value__number_ranges,
  (ProtobufCMessageInit) value__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor result__field_descriptors[2] =
{
  {
    "singleResult",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    offsetof(Result, result_types_case),
    offsetof(Result, singleresult),
    NULL,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "countedResult",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Result, result_types_case),
    offsetof(Result, countedresult),
    &counted_result__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned result__field_indices_by_name[] = {
  1,   /* field[1] = countedResult */
  0,   /* field[0] = singleResult */
};
static const ProtobufCIntRange result__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor result__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Result",
  "Result",
  "Result",
  "",
  sizeof(Result),
  2,
  result__field_descriptors,
  result__field_indices_by_name,
  1,  result__number_ranges,
  (ProtobufCMessageInit) result__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor counted_result__field_descriptors[2] =
{
  {
    "count",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(CountedResult, count),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(CountedResult, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned counted_result__field_indices_by_name[] = {
  0,   /* field[0] = count */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange counted_result__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor counted_result__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CountedResult",
  "CountedResult",
  "CountedResult",
  "",
  sizeof(CountedResult),
  2,
  counted_result__field_descriptors,
  counted_result__field_indices_by_name,
  1,  counted_result__number_ranges,
  (ProtobufCMessageInit) counted_result__init,
  NULL,NULL,NULL    /* reserved[123] */
};
