/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: aggregate.proto */

#ifndef PROTOBUF_C_aggregate_2eproto__INCLUDED
#define PROTOBUF_C_aggregate_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif




/* --- enums --- */

typedef enum _Aggregate {
  AGGREGATE__Minimum = 0,
  AGGREGATE__Maximum = 1,
  AGGREGATE__Average = 2,
  AGGREGATE__Median = 3
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(AGGREGATE)
} Aggregate;

/* --- messages --- */

/* --- per-message closures --- */


/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    aggregate__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_aggregate_2eproto__INCLUDED */
