/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: query_request.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "query_request.pb-c.h"
void   query_request__init
                     (QueryRequest         *message)
{
  static const QueryRequest init_value = QUERY_REQUEST__INIT;
  *message = init_value;
}
size_t query_request__get_packed_size
                     (const QueryRequest *message)
{
  assert(message->base.descriptor == &query_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t query_request__pack
                     (const QueryRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &query_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t query_request__pack_to_buffer
                     (const QueryRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &query_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
QueryRequest *
       query_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (QueryRequest *)
     protobuf_c_message_unpack (&query_request__descriptor,
                                allocator, len, data);
}
void   query_request__free_unpacked
                     (QueryRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &query_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   select__init
                     (Select         *message)
{
  static const Select init_value = SELECT__INIT;
  *message = init_value;
}
size_t select__get_packed_size
                     (const Select *message)
{
  assert(message->base.descriptor == &select__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t select__pack
                     (const Select *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &select__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t select__pack_to_buffer
                     (const Select *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &select__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Select *
       select__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Select *)
     protobuf_c_message_unpack (&select__descriptor,
                                allocator, len, data);
}
void   select__free_unpacked
                     (Select *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &select__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   main_executor__init
                     (MainExecutor         *message)
{
  static const MainExecutor init_value = MAIN_EXECUTOR__INIT;
  *message = init_value;
}
size_t main_executor__get_packed_size
                     (const MainExecutor *message)
{
  assert(message->base.descriptor == &main_executor__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t main_executor__pack
                     (const MainExecutor *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &main_executor__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t main_executor__pack_to_buffer
                     (const MainExecutor *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &main_executor__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MainExecutor *
       main_executor__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MainExecutor *)
     protobuf_c_message_unpack (&main_executor__descriptor,
                                allocator, len, data);
}
void   main_executor__free_unpacked
                     (MainExecutor *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &main_executor__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor query_request__field_descriptors[4] =
{
  {
    "files_names",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(QueryRequest, n_files_names),
    offsetof(QueryRequest, files_names),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "group_columns",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(QueryRequest, n_group_columns),
    offsetof(QueryRequest, group_columns),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "select",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(QueryRequest, n_select),
    offsetof(QueryRequest, select),
    &select__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "executor",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(QueryRequest, executor),
    &main_executor__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned query_request__field_indices_by_name[] = {
  3,   /* field[3] = executor */
  0,   /* field[0] = files_names */
  1,   /* field[1] = group_columns */
  2,   /* field[2] = select */
};
static const ProtobufCIntRange query_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor query_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "QueryRequest",
  "QueryRequest",
  "QueryRequest",
  "",
  sizeof(QueryRequest),
  4,
  query_request__field_descriptors,
  query_request__field_indices_by_name,
  1,  query_request__number_ranges,
  (ProtobufCMessageInit) query_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor select__field_descriptors[2] =
{
  {
    "column",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Select, column),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "function",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Select, function),
    &aggregate__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned select__field_indices_by_name[] = {
  0,   /* field[0] = column */
  1,   /* field[1] = function */
};
static const ProtobufCIntRange select__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor select__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Select",
  "Select",
  "Select",
  "",
  sizeof(Select),
  2,
  select__field_descriptors,
  select__field_indices_by_name,
  1,  select__number_ranges,
  (ProtobufCMessageInit) select__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor main_executor__field_descriptors[3] =
{
  {
    "is_current_node_main",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(MainExecutor, is_current_node_main),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ip_address",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(MainExecutor, ip_address),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "port",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(MainExecutor, port),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned main_executor__field_indices_by_name[] = {
  1,   /* field[1] = ip_address */
  0,   /* field[0] = is_current_node_main */
  2,   /* field[2] = port */
};
static const ProtobufCIntRange main_executor__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor main_executor__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "MainExecutor",
  "MainExecutor",
  "MainExecutor",
  "",
  sizeof(MainExecutor),
  3,
  main_executor__field_descriptors,
  main_executor__field_indices_by_name,
  1,  main_executor__number_ranges,
  (ProtobufCMessageInit) main_executor__init,
  NULL,NULL,NULL    /* reserved[123] */
};
