name: Unit Tests EXECUTOR

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake g++ protobuf-compiler

      - name: Build project
        run: |
          mkdir build && cd build
          cmake -DENABLE_UNIT_TESTING=ON ..
          cmake --build .

      - name: Run tests
        run: |
          cd build
          ctest --output-on-failure
